# Generated by Django 4.1.7 on 2023-03-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', models.ImageField(upload_to='C:\\Users\\dell\\PycharmProjects\\Model_Deployment\\IMAGES\\\\')),
            ],
        ),
    ]
