# Generated by Django 4.1.7 on 2023-04-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imagelist_delete_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('type_of_disease', models.CharField(max_length=100)),
                ('chemical_control', models.CharField(max_length=1000)),
                ('organic_control', models.CharField(max_length=5000)),
                ('also_found_in', models.CharField(max_length=1000)),
                ('avoid_this', models.CharField(max_length=1000)),
            ],
        ),
    ]
